ApDeploymentByScp/ApDeploymentByScp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # 使用 include() 将 users 应用的 urls 模块包含进来
    path('users/',include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ApDeploymentByScp/users/urls.py
from django.urls import path
from . import  views

app_name = "users"
urlpatterns = [
    path('add/',views.add, name='add'),
    path('uploadCad/',views.uploadCad, name='uploadCad'),
    path('deploymentResult/', views.deploymentResult, name='deploymentResult'),
    path('myDeployment/', views.myDeployment, name='myDeployment'),
    path('saveResult/',views.saveResult, name='saveResult'),
    path('login/', views.login, name='login'),
    path('login_ajax/', views.login_ajax, name='login_ajax'),
    path('checkLogin/',views.checkLogin,name='checkLogin'),
    path('register/',views.register,name='register'),
    path('checkRegister/',views.checkRegister,name='checkRegister'),
    path('logout/',views.logout,name='logout'),
    path('deleteRecord/',views.deleteRecord,name='deleteRecord'),
    path('cadSet/',views.cadSet,name='cadSet'),
    path('saveCadParams/', views.saveCadParams,name='saveCadParams')
]

ApDeploymentByScp/users/models.py
from django.db import models

# Create your models here.
# class Test(models.Model): #相当于定义了一个User数据库表，继承自models.Model
#     name = models.CharField(max_length=50) #定义数据表中的字段名及类型
#     # upload_to指定上传文件的位置
#     # 这里指定存放在'/img'目录下
#     headimg = models.FileField(upload_to='img/')
#
#     #返回名称
#     def __str__(self):
#         return self.name

# user表
class User(models.Model):
    username = models.CharField(max_length=64,default="")
    password = models.CharField(max_length=64,default="")

# 部署结果表
class Result(models.Model):
    res_path = models.ImageField(upload_to='img/result/',default="")
    pos_path = models.FileField(upload_to='csv/position_result/',default="")
    ap_num = models.IntegerField(default=0)

# cad表
class Cad(models.Model):
    cad_description = models.CharField(max_length=200,default="")
    cad_path = models.ImageField(upload_to='img/cad/',default="")

# 参数表
class DepParams(models.Model):
    cover_num = models.IntegerField(default=0) #每个位置接收的信号数量约束
    dist_thre = models.IntegerField(default=-1) #设备间隔约束（默认为-1）
    spread_dist = models.IntegerField(default=0) #信号无障碍情况下的传播距离，默认值0
    wall_reduce_dist = models.IntegerField(default=0) #信号遇墙壁衰减距离，默认值0
    glass_reduce_dist = models.IntegerField(default=0) #信号遇玻璃衰减距离，默认值0
    wood_reduce_dist = models.IntegerField(default=0) #信号遇木材衰减距离，默认值0
    other_reduce_dist = models.IntegerField(default=0) #信号遇其他衰减距离，默认值0
    time_limit = models.IntegerField(default=0) #算法运行时间，默认值0

# 部署表
class Deployment(models.Model):
    user = models.ForeignKey('User',null=True, on_delete=models.DO_NOTHING)
    cad = models.ForeignKey('Cad',null=True, on_delete=models.DO_NOTHING)
    res = models.ForeignKey('Result',null=True, on_delete=models.DO_NOTHING)
    dep_param = models.ForeignKey('DepParams',null=True, on_delete=models.DO_NOTHING)





ApDeploymentByScp/users/forms.py
from django import forms

# 表单类用以生成表单
class AddForm(forms.Form):
    filename = forms.CharField(label='文件说明',widget=forms.TextInput(attrs={'class':'form-control'}))
    headimg = forms.FileField()
    cover_num = forms.IntegerField(label='覆盖次数约束',widget=forms.NumberInput(attrs={'class':'form-control'}))
    propagation_distance = forms.IntegerField(label='传播距离',widget=forms.NumberInput(attrs={'class':'form-control'}))
    # reduction distance with regard to different materials
    wall_reduction_distance = forms.IntegerField(label='遇墙衰减距离',widget=forms.TextInput(attrs={'class':'form-control'}))
    glass_reduction_distance = forms.IntegerField(label='遇玻璃衰减距离',widget=forms.TextInput(attrs={'class':'form-control'}))
    wood_reduction_distance = forms.IntegerField(label='遇木材衰减距离',widget=forms.TextInput(attrs={'class':'form-control'}))
    other_reduction_distance = forms.IntegerField(label='遇其他衰减距离',widget=forms.TextInput(attrs={'class':'form-control'}))

    time_limit = forms.IntegerField(label='运行时间',widget=forms.NumberInput(attrs={'class':'form-control'}))
    dist_thre = forms.IntegerField(label='设备间距',widget=forms.NumberInput(attrs={'class':'form-control'}))

#login测试
class LoginForm(forms.Form):
    username = forms.CharField(label="用户名",max_length=128,widget=forms.TextInput(attrs={'class':'form-control form-control-lg','placeholder':'用户名'}))
    password = forms.CharField(label='密码',max_length=256, widget=forms.PasswordInput(attrs={'class':'form-control form-control-lg','placeholder':'密码'}))

ApDeploymentByScp/users/views.py
from django.shortcuts import render
from .models import User, Cad, Result, DepParams, Deployment
from .forms import AddForm, LoginForm
from . import readCad
import os
from django.shortcuts import HttpResponse, render, redirect
import pymysql
import json


def connectToMySQL():
    conn = pymysql.connect(host='127.0.0.1', port=3306, user='root', passwd='hwy960608',
                           db='apdeployment', charset='utf8')
    cursor = conn.cursor(cursor=pymysql.cursors.DictCursor)
    return conn, cursor


def closeSQLConnection(cursor, conn):
    cursor.close()
    conn.close()


# Create your views here.
def uploadCad(request):
    # 判断是否为post方法提交
    if not request.session.has_key('is_login'):
        return render(request, 'users/login.html')
    elif not request.session.has_key('is_set_cad') or not request.session['is_set_cad']:
        return render(request, 'users/cadSet.html')
    elif request.method == "POST":
        print(request.POST)
        print(request.FILES)
        af = AddForm(request.POST, request.FILES)
        # 判断表单值是否合法
        if af.is_valid():
            filename = af.cleaned_data['filename']
            headimg = af.cleaned_data['headimg']
            cover_num = af.cleaned_data['cover_num']
            spread_dist = af.cleaned_data['propagation_distance'] * 1000
            reduce_dist = af.cleaned_data['wall_reduction_distance'] * 1000
            wall_reduce_dist = af.cleaned_data['wall_reduction_distance'] * 1000
            glass_reduce_dist = af.cleaned_data['glass_reduction_distance'] * 1000
            wood_reduce_dist = af.cleaned_data['wood_reduction_distance'] * 1000
            other_reduce_dist = af.cleaned_data['other_reduction_distance'] * 1000

            time_limit = af.cleaned_data['time_limit']
            dist_thre = af.cleaned_data['dist_thre'] * 1000

            # print(filename, cover_num, spread_dist, glass_reduce_dist)
            # cad文件路径
            cad_file_path = os.getcwd().replace("\\", "/") + "/media/img/cad/" + str(headimg)
            if os.path.exists(cad_file_path)==False:
                # 写入数据表Test中
                user = Cad(cad_description=filename, cad_path=headimg)
                user.save()
            #读取cad参数
            minX = int(request.session['minX'])
            minY = int(request.session['minY'])
            maxX = int(request.session['maxX'])
            maxY = int(request.session['maxY'])
            wall_kw = request.session['wall_kw'].split(",")
            glass_kw = request.session['glass_kw'].split(",")
            wood_kw = request.session['wood_kw'].split(",")
            other_kw = request.session['other_kw'].split(",")
            is_merge = int(request.session['is_merge'])
            # 读取cad文件
            readCad.saveLinesByTypes(cad_file_path,minX,minY,maxX,maxY,wall_kw,glass_kw,wood_kw,other_kw)
            # c++处理线条&获取算法的输入文件
            readCad.getInput(spread_dist, wall_reduce_dist, glass_reduce_dist, wood_reduce_dist, other_reduce_dist,
                             cover_num, dist_thre,is_merge)
            # 运行scp代码，输出解
            readCad.runScp(time_limit)
            # 读取解
            readCad.getResPoints(spread_dist, wall_reduce_dist, glass_reduce_dist, wood_reduce_dist, other_reduce_dist,
                                 cover_num, dist_thre,is_merge)
            # 解的可视化
            img_path, pic_name, ap_num, cover_rate = readCad.readScpRes(spread_dist, reduce_dist, cover_num)
            # img_path = readCad.readLines()
            # 展示图片
            # img_data = open(img_path,'rb').read()
            # return HttpResponse(img_data, content_type="image/png")
            # img_relative_path = '/media/img/result/' + pic_name + '.png'
            img_relative_path = '/media/temp_img/positionImg.png'
            cad_relative_path = 'img/cad/'+str(headimg)
            dc = {"resimgpath": img_relative_path, "cover_num": cover_num,
                                   "spread_dist": spread_dist / 1000, "time_limit": time_limit,
                                   "dist_thre": dist_thre / 1000, "ap_num": ap_num,"cover_rate":cover_rate,
                                   "filename": filename,"wall_reduce_dist":wall_reduce_dist / 1000,
                  "glass_reduce_dist":glass_reduce_dist / 1000,"wood_reduce_dist":wood_reduce_dist / 1000,
                  "other_reduce_dist":other_reduce_dist / 1000,"cadpath":cad_relative_path,"pospath":""}
            return render(request, 'users/deploymentResult.html',
                          context={"dc":dc})
            # print(os.getcwd())
            # return render(request, 'users/index.html', context={"user": user})
            # return HttpResponse("上传成功")
            # return HttpResponse(cover_num)
    else:
        print(os.getcwd())
        af = AddForm()
        return render(request, 'users/uploadCad.html', context={'af': af})


def deploymentResult(request):
    contextDict={"resimgpath": "testpath", "cover_num": 3,
                                   "spread_dist": 30, "time_limit": 30,
                                   "dist_thre": 5, "ap_num": 39,
                                   "filename": "testgraph",
                 "wall_reduce_dist":10,"glass_reduce_dist":8,"wood_reduce_dist":5,
                 "other_reduce_dist":10,"cadpath":"cadpath","pospath":""}
    return render(request, 'users/deploymentResult.html',context={'dc':contextDict})

def saveResult(request):
    #conn, cursor = connectToMySQL()
    '''
    insert_sql = "insert into users(username,password) values('210111','hhhhhh')"
    cursor.execute(insert_sql)
    conn.commit()
    '''
    print(request.POST)
    cover_num = request.POST.get("dc[cover_num]")
    spread_dist = request.POST.get("dc[spread_dist]")
    time_limit = request.POST.get("dc[time_limit]")
    dist_thre = request.POST.get("dc[dist_thre]")
    # resImgPath = request.POST.get("dc[resimgpath]")
    cad_description = request.POST.get("dc[filename]")
    wall_reduce_dist = request.POST.get("dc[wall_reduce_dist]")
    glass_reduce_dist = request.POST.get("dc[glass_reduce_dist]")
    wood_reduce_dist = request.POST.get("dc[wood_reduce_dist]")
    other_reduce_dist = request.POST.get("dc[other_reduce_dist]")
    ap_num = request.POST.get("dc[ap_num]")
    cadpath = request.POST.get("dc[cadpath]")
    # pospath = request.POST.get("dc[pospath]")

    print(cover_num,spread_dist,time_limit,dist_thre,cad_description,wall_reduce_dist,glass_reduce_dist,
          wood_reduce_dist,other_reduce_dist,ap_num,cadpath)
    # 获得cad id
    # cad_select_sql = "select id from cad where filepath=%s"
    # cursor.execute(cad_select_sql,[cadpath,])
    # res = cursor.fetchall()
    # if(len(res) == 0):
    #     cad_insert_sql = "insert into cad(filename,filepath) values(%s,%s)"
    #     cursor.execute(cad_insert_sql,[filename,cadpath,])
    #     conn.commit()
    #     cursor.execute(cad_select_sql,[cadpath,])
    #     res = cursor.fetchall()
    # cad_id = res[0]['id']
    # print(cad_id)
    res = Cad.objects.filter(cad_path=cadpath)
    print(len(res))
    print(res)
    if len(res) == 0:
        Cad.objects.create(cad_description=cad_description,cad_path=cadpath)
        res = Cad.objects.filter(cad_path=cadpath)
    print("cad id:",res[0].id)
    cad_i = res[0]
    # 获得参数id
    # param_select_sql = "select id from params where cover_num=%s and dist_thre=%s and spread_dist=%s and " \
    #                    "wall_reduce_dist=%s and glass_reduce_dist=%s and wood_reduce_dist=%s and other_reduce_dist=%s and " \
    #                    "time_limit=%s"
    # cursor.execute(param_select_sql,[cover_num,dist_thre,spread_dist,wall_reduce_dist,glass_reduce_dist,
    #                                  wood_reduce_dist,other_reduce_dist,time_limit,])
    # res = cursor.fetchall()
    # if(len(res) == 0):
    #     param_insert_sql = "insert into params(cover_num,dist_thre,spread_dist, wall_reduce_dist, glass_reduce_dist," \
    #                        "wood_reduce_dist, other_reduce_dist, time_limit) values(%s,%s,%s,%s,%s,%s,%s,%s)"
    #     cursor.execute(param_insert_sql, [cover_num, dist_thre, spread_dist, wall_reduce_dist, glass_reduce_dist,
    #                                       wood_reduce_dist, other_reduce_dist, time_limit,])
    #     conn.commit()
    #     cursor.execute(param_select_sql, [cover_num, dist_thre, spread_dist, wall_reduce_dist, glass_reduce_dist,
    #                                       wood_reduce_dist, other_reduce_dist, time_limit,])
    #     res = cursor.fetchall()
    # param_id = res[0]['id']
    # print(param_id)
    res = DepParams.objects.filter(cover_num=cover_num,dist_thre=dist_thre,spread_dist=spread_dist,
                                   wall_reduce_dist=wall_reduce_dist,glass_reduce_dist=glass_reduce_dist,
                                   wood_reduce_dist=wood_reduce_dist,other_reduce_dist=other_reduce_dist,
                                   time_limit=time_limit)
    if len(res) == 0:
        DepParams.objects.create(cover_num=cover_num,dist_thre=dist_thre,spread_dist=spread_dist,
                                 wall_reduce_dist=wall_reduce_dist,glass_reduce_dist=glass_reduce_dist,
                                 wood_reduce_dist=wood_reduce_dist,other_reduce_dist=other_reduce_dist,
                                 time_limit=time_limit)
        res = DepParams.objects.filter(cover_num=cover_num, dist_thre=dist_thre, spread_dist=spread_dist,
                                       wall_reduce_dist=wall_reduce_dist, glass_reduce_dist=glass_reduce_dist,
                                       wood_reduce_dist=wood_reduce_dist, other_reduce_dist=other_reduce_dist,
                                       time_limit=time_limit)
    print("param id:",res[0].id)
    param_i = res[0]
    # # 获得结果id

ApDeploymentByScp/templates/users/deploymentResult.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css"
          integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">-->
    <link rel="stylesheet" href="/static/assets/css/shared/style.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <script src="http://i.gtimg.cn/qzone/biz/gdt/lib/jquery/jquery-2.1.4.js?max_age=31536000"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <!--<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- plugins:css -->
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/ionicons/css/ionicons.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/typicons/src/font/typicons.css">
    <link rel="stylesheet" href="/static/assets/vendors/iconfonts/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="/static/assets/vendors/css/vendor.bundle.addons.css">
    <!-- endinject -->
    <!-- plugin css for this page -->
    <!-- End plugin css for this page -->
    <!-- inject:css -->

    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="/static/assets/css/demo_1/style.css">
    <!-- End Layout styles -->
    <title>Title</title>
</head>
<body>
{% if request.session.is_login %}
<form class="needs-validation" enctype="multipart/form-data" method="POST" id="resform">
    {% csrf_token %}
    <div class="container-scroller">
        <div class="container-fluid page-body-wrapper">
            <!-- 左侧导航栏 -->
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item nav-profile">
                        <a href="#" class="nav-link">
                            <div class="text-wrapper">
                                <p class="profile-name" style="color:white;font-size: 20px">{{ request.session.username }}</p>
                                <p class="designation">欢迎你</p>
                            </div>
                        </a>
                    </li>
                    <li class="nav-item nav-category">Main Menu</li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:uploadCad' %}">
                            <i class="menu-icon typcn typcn-document-text"></i>
                            <span class="menu-title">开始部署</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:myDeployment' %}">
                            <i class="menu-icon typcn typcn-shopping-bag"></i>
                            <span class="menu-title">我的部署</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:cadSet' %}">
                            <i class="menu-icon typcn typcn-document-text"></i>
                            <span class="menu-title">CAD设置</span>
                        </a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">
                                <i class="menu-icon typcn typcn-shopping-bag"></i>
                                <span class="menu-title">退出登录</span>
                            </a>
                        </li>
                </ul>
            </nav>
            <!-- 部署结果展示 -->
            <div class="main-panel">
                <div class="content-wrapper">
                    <div class="row">
                        <div class="col-lg-6 grid-margin stretch-card">
                            <div class="card">
                                <div class="p-4 pr-5 border-bottom bg-light d-flex justify-content-between">
                                    <h4 class="card-title mb-0"><b>部署结果</b></h4>
                                    <div class="d-flex align-items-center pb-2">
                                        <div class="dot-indicator bg-danger mr-2"></div>
                                        <p class="mb-0">部署点</p>
                                    </div>
                                </div>
                                <div class="card-body">
                                    <img class="mt-4" style="height:300px"
                                         src={{ dc.resimgpath }} }}>
                                    <div class="d-flex pt-3 border-top">
                                        <p class="mb-0 font-weight-semibold"><span
                                                class="dot-indicator bg-success"></span> 覆盖率</p>
                                        <p class="mb-0 ml-auto text-primary">{{ dc.cover_rate }}%</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 grid-margin stretch-card">
                            <div class="card">
                                <div class="p-4 pr-5 border-bottom bg-light d-flex justify-content-between">
                                    <h4 class="card-title mb-0"><b>部署信息</b></h4>
                                </div>
                                <div class="card-body">
                                    <table class="table table-striped">
                                        <tbody>
                                        <tr>
                                            <td> 文件说明 </td>
                                            <td> {{ dc.filename }} </td>
                                        </tr>
                                        <tr>
                                            <td> 信号覆盖次数 </td>
                                            <td>{{ dc.cover_num }}次</td>
                                        </tr>
                                        <tr>
                                            <td> 设备最低间隔 </td>
                                            <td> {{ dc.dist_thre }}m </td>
                                        </tr>
                                        <tr>
                                            <td> 信号传播距离 </td>
                                            <td> {{ dc.spread_dist }}m </td>
                                        </tr>
                                        <tr>
                                            <td> 算法运行时间 </td>
                                            <td> {{ dc.time_limit }}s </td>
                                        </tr>
                                        <tr>
                                            <td><b> 部署结果 </b></td>
                                            <td><b style="color:red;font-size:28px;">{{ dc.ap_num }}</b></td>
                                        </tr>
                                        </tbody>
                                    </table>
                                    <div class="row pt-5">
                                        <div class="col-lg-6 pl-5">
                                            <button type="button" class="btn btn-danger btn-rounded btn-fw" data-toggle="modal"
                                                            data-target="#checkSaveModal">保存结果</button>
                                        </div>
                                        <div class="col-lg-6 pr-5">
                                            <a href="{% url 'users:uploadCad' %}">
                                                <button type="button" class="btn btn-info btn-rounded btn-fw">重新部署</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <p>
</p>
</form>
{% else %}
    <li><a href="{% url 'users:login' %}">还没登录，前去登录</a></li>
{% endif %}
<!-- 部署信息查看模态 -->
<div class="modal fade" id="checkSaveModal" tabindex="-1" role="dialog" aria-labelledby="checkSaveModalLabel"
     aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="paramsModalLabel">部署参数信息</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                确定要保存吗？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary btn-danger" data-dismiss="modal" onclick="save_result({{ dc }})">是</button>
                <button type="button" class="btn btn-secondary btn-success" data-dismiss="modal">否</button>
            </div>
        </div>
    </div>
</div>

<script>
        function save_result (dc){
            var csrfToken = $("[name='csrfmiddlewaretoken']").val();
            $.ajax({
                type: "POST",//预期服务器返回的数据类型
                dataType:"json",
                url: "/users/saveResult/" ,//url
                data:{"dc":dc,'csrfmiddlewaretoken':csrfToken},
                success: function (arg) {
                    console.log(arg);//打印服务端返回的数据(调试用)
                    if(arg.status == "success"){
                        console.log("is suc");
                        {# 判断确实正确入库之后提示#}
                        toastr.success("保存成功，可前往我的部署页面查看");
                     }
                 }
            })
        }
    </script>

<!-- container-scroller -->
<!-- plugins:js -->
<script src="/static/assets/vendors/js/vendor.bundle.base.js"></script>
<script src="/static/assets/vendors/js/vendor.bundle.addons.js"></script>
<!-- endinject -->
<!-- Plugin js for this page-->
<!-- End plugin js for this page-->
<!-- inject:js -->
<script src="/static/assets/js/shared/off-canvas.js"></script>
<script src="/static/assets/js/shared/misc.js"></script>
<!-- endinject -->
<!-- Custom js for this page-->
<script src="/static/assets/js/shared/chart.js"></script>
<!-- End custom js for this page-->

</body>

</html>

ApDeploymentByScp/templates/users/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    <p>
        {{ user.name }}
    </p>
    <img width="50%" height="50%" src="/media/{{ user.headimg }}">

</body>
</html>